1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy package under the name np

In [2]:
print(np.version.full_version)
print(np.__config__.CONFIG)

2.5.0
{'Compilers': {'c': {'name': 'msvc', 'linker': 'link', 'version': '19.44.35228', 'commands': 'cl'}, 'cython': {'name': 'cython', 'linker': 'cython', 'version': '3.2.5', 'commands': 'cython'}, 'c++': {'name': 'msvc', 'linker': 'link', 'version': '19.44.35228', 'commands': 'cl'}}, 'Machine Information': {'host': {'cpu': 'x86_64', 'family': 'x86_64', 'endian': 'little', 'system': 'windows'}, 'build': {'cpu': 'x86_64', 'family': 'x86_64', 'endian': 'little', 'system': 'windows'}}, 'Build Dependencies': {'blas': {'name': 'scipy-openblas', 'found': True, 'version': '0.3.33.112.0', 'detection method': 'pkgconfig', 'include directory': 'C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3pm2x0xb/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include', 'lib directory': 'C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3pm2x0xb/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib', 'openblas configuration': 'OpenBLAS 0.3.33.112.0  USE64BITINT DYNAMIC_ARCH NO_AFFIN

3. Create a null vector of size 10

In [3]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [4]:
mem_size = np.size(null_vec)
print(mem_size)

10


5. How to get the documentation of the numpy add function from the command line? 

In [5]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [6]:
"python -m pydoc numpy.add"

'python -m pydoc numpy.add'

6. Create a null vector of size 10 but the fifth value which is 1 

In [7]:
nv10 = np.zeros(10)
nv10[4] = 1
print(nv10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [8]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [9]:
print("Previous : \n", v)

v[:] = v[::-1]
print("Reversed with v[:] = v[::-1] :\n", v)

u = np.flip(v)
print("With np.flip(v)\n", u)

Previous : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed with v[:] = v[::-1] :
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
With np.flip(v)
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
v = np.arange(0,9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
v = [1,2,0,0,4,0]
v = np.array(v)
r = []
for i in range(v.size):
    r.append(i)
    print(f"{i}, ") if v[i] == 0 else None


2, 
3, 
5, 


11. Create a 3x3 identity matrix

In [12]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values

In [13]:
v = np.random.random((3,3,3))
print(v)

[[[0.02091341 0.08803761 0.49981176]
  [0.85679969 0.22166226 0.64390846]
  [0.93720027 0.6391666  0.96504247]]

 [[0.25222681 0.33586344 0.67762158]
  [0.10324686 0.41906634 0.98645524]
  [0.65339906 0.0762453  0.28111063]]

 [[0.08548957 0.86551446 0.69768378]
  [0.62386443 0.18496887 0.89567908]
  [0.56046247 0.02272022 0.92056681]]]


13. Create a 10x10 array with random values and find the minimum and maximum values 

In [14]:
v = np.random.random((10,10))
min = v.min()
max = v.max()
print(f"Min: {min}\nMax: {max}")

Min: 0.01491592438697853
Max: 0.9999064626191755


14. Create a random vector of size 30 and find the mean value

In [15]:
v = np.random.random((30))
print(f"Mean value : {v.mean()}")

Mean value : 0.5076772915970444


15. Create a 2d array with 1 on the border and 0 inside 

In [16]:
v = np.ones((5,5))
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [17]:
v = np.random.random((2,2))*10
print(v)

v = np.pad(v, pad_width=1, mode='constant', constant_values=0)
print(f"New v: {v}")

[[0.15004024 9.09301623]
 [1.91315583 6.70000271]]
New v: [[0.         0.         0.         0.        ]
 [0.         0.15004024 9.09301623 0.        ]
 [0.         1.91315583 6.70000271 0.        ]
 [0.         0.         0.         0.        ]]


17. What is the result of the following expression? 

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

**ANSWER**

- 0
- True
- Exception
- 0
- 1
- False

---
Test if it is true

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [19]:
v = np.random.random((5,5))*10
c = np.array([1, 2, 3, 4])
for i in range(c.size):
    for j in range(c.size):
        if i == j:
            v[i+1, j] = c[j] 

print(v)

[[0.67312515 6.57794829 9.20813699 8.98658261 5.39616563]
 [1.         5.15147748 3.68445934 6.1259347  8.81682601]
 [2.7255869  2.         5.61897107 9.72719836 0.23578726]
 [1.80161955 4.27983139 3.         1.61900029 1.50385808]
 [6.78664111 2.00889459 8.33513537 4.         5.74737345]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [26]:
v = np.ones(64)
for i in range(64):
    if i%2 == 0:
        v[i] = 0
v = v.reshape(8,8)
print(v)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
# Total elements
shape = (6, 7, 8)
total = np.prod(shape)
print(f"Total elements: {total}") 

# Flatten and find the 100th element (index 99 in 0-based)
flat_index = 99  # 0-based index for 100th element

# Method 1: Using np.unravel_index()
index = np.unravel_index(flat_index, shape)
print(f"Index (x,y,z): {index}") 

Total elements: 336
Index (x,y,z): (np.int64(1), np.int64(5), np.int64(3))
