1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy package under the name np

In [2]:
print(np.version.full_version)
print(np.__config__.CONFIG)

2.5.0
{'Compilers': {'c': {'name': 'msvc', 'linker': 'link', 'version': '19.44.35228', 'commands': 'cl'}, 'cython': {'name': 'cython', 'linker': 'cython', 'version': '3.2.5', 'commands': 'cython'}, 'c++': {'name': 'msvc', 'linker': 'link', 'version': '19.44.35228', 'commands': 'cl'}}, 'Machine Information': {'host': {'cpu': 'x86_64', 'family': 'x86_64', 'endian': 'little', 'system': 'windows'}, 'build': {'cpu': 'x86_64', 'family': 'x86_64', 'endian': 'little', 'system': 'windows'}}, 'Build Dependencies': {'blas': {'name': 'scipy-openblas', 'found': True, 'version': '0.3.33.112.0', 'detection method': 'pkgconfig', 'include directory': 'C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3pm2x0xb/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include', 'lib directory': 'C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3pm2x0xb/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib', 'openblas configuration': 'OpenBLAS 0.3.33.112.0  USE64BITINT DYNAMIC_ARCH NO_AFFIN

3. Create a null vector of size 10

In [3]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [4]:
mem_size = np.size(null_vec)
print(mem_size)

10


5. How to get the documentation of the numpy add function from the command line? 

In [5]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [6]:
"python -m pydoc numpy.add"

'python -m pydoc numpy.add'

6. Create a null vector of size 10 but the fifth value which is 1 

In [7]:
nv10 = np.zeros(10)
nv10[4] = 1
print(nv10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [8]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [9]:
print("Previous : \n", v)

v[:] = v[::-1]
print("Reversed with v[:] = v[::-1] :\n", v)

u = np.flip(v)
print("With np.flip(v)\n", u)

Previous : 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed with v[:] = v[::-1] :
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
With np.flip(v)
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
v = np.arange(0,9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [20]:
v = [1,2,0,0,4,0]
v = np.array(v)
r = []
for i in range(v.size):
    r.append(i)
    print(f"{i}, ") if v[i] == 0 else None


2, 
3, 
5, 
